### ISSUE TITLE
New Instagram API Restrictions: Access Token Invalid Error with current implementation?

### ISSUE THREAD

**Issue by mittaluday** [cmaseattle/instagram-grid#26]
Instagram changed its permissions structure and has forced the [sandbox mode](https://www.instagram.com/developer/review/) onto clients today. I was using this project with [my website](http://mittaluday.com/about.html), but I get an invalid token error after today. 

Probably need to review how authentication is handled now with this new permissions structure?

**Comment by mittaluday** [comment]
The following URL in instagram-grid.js needs to be modified to include an access_token and there is no need for putting the client_id in the request parameters. This requirement can be seen in the [Instagram API changelog](https://www.instagram.com/developer/changelog/)

`var url = params._local ? params._local : 'https://api.instagram.com/v1/users/'+params._userID+'/media/recent/?client_id='+params._clientid+'&count='+params.total;`

The access token may be received by following the authorization steps as mentioned [here](https://www.instagram.com/developer/authentication/). I made the changes to my fork and will issue a pull request for you to review.

**Comment by mapsam** [comment]
Thanks @mittaluday - I haven't been using the library at all, didn't realize Instagram changed their API policies. If you open up a PR, mind updating the README as well?

**Comment by mapsam** [comment]
Ah, see that you've already done this in #28. Nice work!
